# Generated by Django 4.1.4 on 2022-12-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('url_name', models.CharField(max_length=100, verbose_name='Имя URL')),
            ],
            options={
                'verbose_name': 'Элемент навигации',
                'verbose_name_plural': 'Элементы навигации',
            },
        ),
    ]
