# Generated by Django 4.1.4 on 2022-12-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navelement',
            old_name='name',
            new_name='label',
        ),
    ]
