# Generated by Django 4.1.4 on 2022-12-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0002_rename_name_navelement_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavElement',
        ),
    ]
