# Generated by Django 4.1.4 on 2022-12-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25, verbose_name='Название')),
                ('content', models.CharField(max_length=100, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Элемент подвала',
                'verbose_name_plural': 'Элементы подвала',
            },
        ),
    ]
