# Generated by Django 4.1.4 on 2022-12-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0005_footerelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerelement',
            name='label',
            field=models.CharField(blank=True, max_length=25, verbose_name='Название'),
        ),
    ]
