# Generated by Django 4.1.4 on 2022-12-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0006_alter_footerelement_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('logo', models.FileField(upload_to='logos', verbose_name='Логотип')),
                ('is_logo_shown', models.BooleanField(default=True, verbose_name='Отображать логотип')),
                ('is_prof_name_shown', models.BooleanField(default=True, verbose_name='Отображать название профессии')),
                ('is_chosen', models.BooleanField(default=False, verbose_name='Выбран')),
            ],
            options={
                'verbose_name': 'Вариант шапки',
                'verbose_name_plural': 'Варианты шапки',
            },
        ),
    ]
