# Generated by Django 4.1.4 on 2023-01-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0008_header_is_logo_changed_alter_header_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название профессии')),
                ('text_block_1', models.TextField(blank=True, verbose_name='Блок текста 1')),
                ('image_1', models.ImageField(blank=True, upload_to='photos/', verbose_name='Изображение 1')),
                ('image_1_caption', models.CharField(max_length=100, verbose_name='Подпись изображения 1')),
                ('text_block_2', models.TextField(blank=True, verbose_name='Блок текста 2')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/', verbose_name='Изображение 2')),
                ('image_2_caption', models.CharField(max_length=100, verbose_name='Подпись изображения 2')),
                ('text_block_3', models.TextField(blank=True, verbose_name='Блок текста 3')),
                ('image_3', models.ImageField(blank=True, upload_to='photos/', verbose_name='Изображение 3')),
                ('image_3_caption', models.CharField(max_length=100, verbose_name='Подпись изображения 3')),
                ('years_stats', models.FileField(blank=True, upload_to='stats/', verbose_name='Статистика по годам')),
                ('years_salary_graph', models.FileField(blank=True, upload_to='graphs/years', verbose_name='График: Динамика уровня зарплат по годам')),
                ('years_vac_num_graph', models.FileField(blank=True, upload_to='graphs/years', verbose_name='График: Динамика количества вакансий по годам')),
                ('years_salary_for_prof_graph', models.FileField(blank=True, upload_to='graphs/years', verbose_name='График: Динамика уровня зарплат по годам для выбранной профессии')),
                ('years_vac_num_for_prof_graph', models.FileField(blank=True, upload_to='graphs/years', verbose_name='График: Динамика количества вакансий по годам для выбранной профессии')),
                ('years_salary_comparison_graph', models.FileField(blank=True, upload_to='graphs/years', verbose_name='График: Динамика уровня зарплат по годам (сравнение)')),
                ('years_vac_num_comparison_graph', models.FileField(blank=True, upload_to='graphs/years', verbose_name='График: Динамика количества вакансий по годам (сравнение)')),
                ('areas_stats', models.FileField(blank=True, upload_to='stats/', verbose_name='Статистика по регионам')),
                ('areas_salary_graph', models.FileField(blank=True, upload_to='graphs/areas', verbose_name='График: Уровень зарплат по городам')),
                ('areas_vac_fractions_graph', models.FileField(blank=True, upload_to='graphs/areas', verbose_name='График: Доля вакансий по городам')),
                ('skills_stats', models.FileField(blank=True, upload_to='stats/', verbose_name='Статистика по востребованности навыков')),
                ('top_skills_total_graph', models.FileField(blank=True, upload_to='graphs/skills', verbose_name='График: Востребованность навыков за всё время')),
                ('is_chosen', models.BooleanField(default=False, verbose_name='Выбрана')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
    ]
