# Generated by Django 4.1.4 on 2023-01-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0008_header_is_logo_changed_alter_header_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название профессии')),
                ('text_block_1', models.TextField(blank=True, verbose_name='Блок текста 1')),
                ('image_1', models.ImageField(blank=True, upload_to='photos/', verbose_name='Изображение 1')),
                ('image_1_caption', models.CharField(blank=True, max_length=100, verbose_name='Подпись изображения 1')),
                ('text_block_2', models.TextField(blank=True, verbose_name='Блок текста 2')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/', verbose_name='Изображение 2')),
                ('image_2_caption', models.CharField(blank=True, max_length=100, verbose_name='Подпись изображения 2')),
                ('text_block_3', models.TextField(blank=True, verbose_name='Блок текста 3')),
                ('image_3', models.ImageField(blank=True, upload_to='photos/', verbose_name='Изображение 3')),
                ('image_3_caption', models.CharField(blank=True, max_length=100, verbose_name='Подпись изображения 3')),
                ('is_chosen', models.BooleanField(default=False, verbose_name='Выбрана')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='DemandOneVarGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('label', models.CharField(max_length=150, verbose_name='Подпись')),
                ('graph', models.FileField(upload_to='graphs/demand', verbose_name='График')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отображать')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.profession', verbose_name='Профессия')),
            ],
        ),
    ]
