# Generated by Django 4.1.4 on 2023-01-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0009_profession_demandonevargraph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandonevargraph',
            options={'verbose_name': 'График раздела "Востребованность" с одной переменной', 'verbose_name_plural': 'Графики раздела "Востребованность" с одной переменной'},
        ),
    ]
