# Generated by Django 4.1.4 on 2023-01-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0009_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='image_1_caption',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подпись изображения 1'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='image_2_caption',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подпись изображения 2'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='image_3_caption',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подпись изображения 3'),
        ),
    ]
