# Generated by Django 4.1.4 on 2023-01-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0010_alter_demandonevargraph_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonDemandGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('label', models.CharField(max_length=150, verbose_name='Подпись')),
                ('graph', models.FileField(upload_to='graphs/demand', verbose_name='График')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отображать')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'График раздела "Востребованность", сравнительный',
                'verbose_name_plural': 'Графики раздела "Востребованность", сравнительные',
            },
        ),
        migrations.CreateModel(
            name='NonProfConnectedDemandGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('label', models.CharField(max_length=150, verbose_name='Подпись')),
                ('graph', models.FileField(upload_to='graphs/demand', verbose_name='График')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'График раздела "Востребованность", не связанный с профессией',
                'verbose_name_plural': 'Графики раздела "Востребованность", не связанные с профессией',
            },
        ),
        migrations.CreateModel(
            name='ProfConnectedDemandGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('label', models.CharField(max_length=150, verbose_name='Подпись')),
                ('graph', models.FileField(upload_to='graphs/demand', verbose_name='График')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отображать')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'График раздела "Востребованность" с одной переменной, связанный с профессией',
                'verbose_name_plural': 'Графики раздела "Востребованность" с одной переменной, связанные с профессией',
            },
        ),
        migrations.DeleteModel(
            name='DemandOneVarGraph',
        ),
    ]
