# Generated by Django 4.1.4 on 2023-01-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0011_comparisondemandgraph_nonprofconnecteddemandgraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisondemandgraph',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nonprofconnecteddemandgraph',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='profconnecteddemandgraph',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
