# Generated by Django 4.1.4 on 2023-01-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0012_alter_comparisondemandgraph_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('label', models.CharField(max_length=150, verbose_name='Подпись')),
                ('graph', models.FileField(upload_to='graphs/demand', verbose_name='График')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'График раздела "Востребованность", сравнительный',
                'verbose_name_plural': 'Графики раздела "Востребованность", сравнительные',
            },
        ),
        migrations.CreateModel(
            name='NonProfConnectedGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('label', models.CharField(max_length=150, verbose_name='Подпись')),
                ('graph', models.FileField(upload_to='graphs/demand', verbose_name='График')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'График раздела "Востребованность", не связанный с профессией',
                'verbose_name_plural': 'Графики раздела "Востребованность", не связанные с профессией',
            },
        ),
        migrations.CreateModel(
            name='NonProfConnectedTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, verbose_name='Название')),
                ('keys_label', models.CharField(max_length=50, verbose_name='Название левого столбца')),
                ('values_label', models.CharField(max_length=50, verbose_name='Название правого столбца')),
                ('data', models.FileField(upload_to='stat_data/', verbose_name='Данные')),
                ('max_rows', models.IntegerField(default=15, verbose_name='Максимальное кол-во строк')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Таблица, не связанная с профессией',
                'verbose_name_plural': 'Таблицы, не связанные с профессией',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название страницы')),
                ('label', models.CharField(max_length=70, verbose_name='Отображаемое имя')),
            ],
        ),
        migrations.CreateModel(
            name='ProfConnectedGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('label', models.CharField(max_length=150, verbose_name='Подпись')),
                ('graph', models.FileField(upload_to='graphs/demand', verbose_name='График')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отображать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.page', verbose_name='Страница')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'График раздела "Востребованность" с одной переменной, связанный с профессией',
                'verbose_name_plural': 'Графики раздела "Востребованность" с одной переменной, связанные с профессией',
            },
        ),
        migrations.CreateModel(
            name='ProfConnectedTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, verbose_name='Название')),
                ('keys_label', models.CharField(max_length=50, verbose_name='Название левого столбца')),
                ('values_label', models.CharField(max_length=50, verbose_name='Название правого столбца')),
                ('data', models.FileField(upload_to='stat_data/', verbose_name='Данные')),
                ('max_rows', models.IntegerField(default=15, verbose_name='Максимальное кол-во строк')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отображать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.page', verbose_name='Страница')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Таблица, связанная с профессией',
                'verbose_name_plural': 'Таблицы, связанные с профессией',
            },
        ),
        migrations.RemoveField(
            model_name='comparisondemandgraph',
            name='profession',
        ),
        migrations.DeleteModel(
            name='NonProfConnectedDemandGraph',
        ),
        migrations.RemoveField(
            model_name='profconnecteddemandgraph',
            name='profession',
        ),
        migrations.DeleteModel(
            name='ComparisonDemandGraph',
        ),
        migrations.DeleteModel(
            name='ProfConnectedDemandGraph',
        ),
        migrations.AddField(
            model_name='nonprofconnectedtabledata',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.page', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='nonprofconnectedgraph',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.page', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='comparisongraph',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.page', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='comparisongraph',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.profession', verbose_name='Профессия'),
        ),
    ]
