# Generated by Django 4.1.4 on 2023-01-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0013_comparisongraph_nonprofconnectedgraph_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparisongraph',
            options={'verbose_name': 'График  сравнительный', 'verbose_name_plural': 'Графики сравнительные'},
        ),
        migrations.AlterModelOptions(
            name='nonprofconnectedgraph',
            options={'verbose_name': 'График, не связанный с профессией', 'verbose_name_plural': 'Графики, не связанные с профессией'},
        ),
        migrations.AlterModelOptions(
            name='profconnectedgraph',
            options={'verbose_name': 'График, связанный с профессией', 'verbose_name_plural': 'Графики, связанные с профессией'},
        ),
    ]
