# Generated by Django 4.1.4 on 2023-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0014_alter_comparisongraph_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisongraph',
            name='label',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='nonprofconnectedgraph',
            name='label',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='profconnectedgraph',
            name='label',
            field=models.CharField(blank=True, max_length=150, verbose_name='Подпись'),
        ),
    ]
