# Generated by Django 4.1.4 on 2023-01-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0015_alter_comparisongraph_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, verbose_name='Название')),
                ('keys_label', models.CharField(max_length=50, verbose_name='Название левого столбца')),
                ('values_label', models.CharField(max_length=50, verbose_name='Название правого столбца')),
                ('data', models.FileField(upload_to='stat_data/', verbose_name='Данные')),
                ('max_rows', models.IntegerField(default=10, verbose_name='Максимальное кол-во строк для одной таблицы')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отображать')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profession.page', verbose_name='Страница')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profession.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Группа таблиц, содержащих различные варианты одного признака',
                'verbose_name_plural': 'Группы таблиц, содержащих различные варианты одного признака',
            },
        ),
    ]
