# Generated by Django 4.1.4 on 2023-01-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0016_multitabledata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiTableData',
            new_name='TableSeriesData',
        ),
    ]
