# Generated by Django 4.1.4 on 2023-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0017_rename_multitabledata_tableseriesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('header', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
            },
        ),
    ]
