# Generated by Django 4.1.4 on 2023-01-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0018_homesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSettings',
        ),
    ]
