# Generated by Django 4.1.4 on 2023-01-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0020_page_header_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('graphs_block_header', models.CharField(max_length=150)),
                ('one_var_graphs_header', models.CharField(max_length=250)),
                ('comparison_graphs_header', models.CharField(max_length=250)),
                ('tables_block_header', models.CharField(max_length=150)),
            ],
        ),
    ]
