# Generated by Django 4.1.4 on 2023-01-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0024_geographypagesettings_skillspagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastVacanciesPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('vac_name_label', models.CharField(max_length=150)),
                ('vac_description_label', models.CharField(max_length=150)),
                ('vac_key_skills_label', models.CharField(max_length=150)),
                ('vac_employer_name_label', models.CharField(max_length=150)),
                ('vac_salary_label', models.CharField(max_length=150)),
                ('vac_area_name_label', models.CharField(max_length=150)),
                ('vac_published_at_label', models.CharField(max_length=150)),
                ('is_chosen', models.BooleanField(default=True)),
            ],
        ),
    ]
