# Generated by Django 4.1.4 on 2023-01-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0025_lastvacanciespagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastvacanciespagesettings',
            name='is_chosen',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='lastvacanciespagesettings',
            name='vac_area_name_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='lastvacanciespagesettings',
            name='vac_description_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='lastvacanciespagesettings',
            name='vac_employer_name_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='lastvacanciespagesettings',
            name='vac_key_skills_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='lastvacanciespagesettings',
            name='vac_name_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='lastvacanciespagesettings',
            name='vac_published_at_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='lastvacanciespagesettings',
            name='vac_salary_label',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
