# Generated by Django 4.1.4 on 2023-01-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0026_alter_lastvacanciespagesettings_is_chosen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastvacanciespagesettings',
            name='vac_description_label',
        ),
        migrations.RemoveField(
            model_name='lastvacanciespagesettings',
            name='vac_name_label',
        ),
    ]
