# Generated by Django 4.1.4 on 2023-01-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0028_lastvacanciespagesettings_vac_description_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastvacanciespagesettings',
            name='vacancies_count',
            field=models.IntegerField(default=10),
        ),
    ]
